SELECT * FROM COVIDDEATHS
LIMIT 5

SELECT * FROM COVIDVACCINATIONS

--Total cases, deaths, and death rate globally--
SELECT CONTINENT,
SUM(NEW_CASES) AS TOTAL_NEW_CASES,
SUM(NEW_DEATHS) AS TOTAL_DEATH_CASES
FROM COVIDDEATHS
GROUP BY CONTINENT

--Daily Trend: Cases, Deaths & Death Rate Over Time--
SELECT DATE,
SUM(NEW_CASES) AS DAILY_CASE,
SUM(NEW_DEATHS) AS DAILY_DEATHS,
ROUND(SUM(new_deaths) * 100.0 / NULLIF(SUM(new_cases), 0), 2) AS DAILY_DEATH_RATE 
FROM COVIDDEATHS
GROUP BY DATE
ORDER BY DATE

--Monthly Trend: Cases, Deaths & Death Rate Over Time--

SELECT TO_CHAR(DATE_TRUNC('MONTH', DATE),'YYYY-MM') AS MONTHLY,
SUM(NEW_CASES) AS MONTHLY_CASE,
SUM(NEW_DEATHS) AS MONTHLY_DEATHS,
ROUND(SUM(new_deaths) * 100.0 / NULLIF(SUM(new_cases), 0), 2) AS MONTHLY_DEATH_RATE 
FROM COVIDDEATHS
GROUP BY MONTHLY
ORDER BY MONTHLY

--PEAK DAYS FOR NEW CASES AND DEATHS
SELECT DATE, LOCATION, CONTINENT, NEW_CASES AS PEAK_CASE, NEW_DEATHS AS PEAK_DEATHS
FROM COVIDDEATHS
WHERE NEW_CASES = (SELECT MAX(NEW_CASES) FROM COVIDDEATHS)
   OR NEW_DEATHS = (SELECT MAX(NEW_DEATHS) FROM COVIDDEATHS)
ORDER BY DATE;


--Find the peak days for new cases and deaths per continent

SELECT CONTINENT, DATE, NEW_CASES AS PEAK_CASE
FROM COVIDDEATHS
WHERE (CONTINENT, NEW_CASES) IN (
    SELECT CONTINENT, MAX(NEW_CASES)
    FROM COVIDDEATHS
    GROUP BY CONTINENT	
);

--Find the top 10 countries with the highest total cases.

SELECT LOCATION, SUM(NEW_CASES) AS TOTAL_CASES FROM COVIDDEATHS
GROUP BY LOCATION
ORDER BY TOTAL_CASES DESC
LIMIT 10

--Find countries with the highest death rate.
SELECT LOCATION, SUM(NEW_DEATHS) AS TOTAL_DEATHS, SUM(NEW_CASES) AS TOTAL_CASES, 
ROUND((SUM(NEW_DEATHS) / NULLIF(SUM(NEW_CASES), 0) * 100),2) AS DEATH_RATE
FROM COVIDDEATHS
GROUP BY LOCATION
HAVING (SUM(NEW_DEATHS) / NULLIF(SUM(NEW_CASES), 0) * 100) IS NOT NULL
ORDER BY DEATH_RATE DESC
LIMIT 10


--Calculate the moving average of new cases and deaths over time.

SELECT LOCATION, 
       DATE, 
       NEW_CASES, 
       NEW_DEATHS,
       AVG(NEW_CASES) OVER (PARTITION BY LOCATION ORDER BY DATE ROWS 6 PRECEDING) AS MOVING_AVG_CASES,
       AVG(NEW_DEATHS) OVER (PARTITION BY LOCATION ORDER BY DATE ROWS 6 PRECEDING) AS MOVING_AVG_DEATHS
FROM COVIDDEATHS;

--Analyze COVID-19 trends for a specific country (e.g., USA, India, Brazil).
SELECT CD.LOCATION, SUM(CD.NEW_CASES) AS TOTAL_CASES, SUM(CD.NEW_DEATHS) AS TOTAL_DEATHS, SUM(CV.NEW_VACCINATIONS) AS TOTAL_VACCINATIONS,
ROUND(SUM(CD.NEW_CASES) / NULLIF(SUM(CV.NEW_VACCINATIONS), 0) * 100, 2) AS VACCINATION_RATE
FROM COVIDDEATHS CD
JOIN COVIDVACCINATIONS CV 
ON CD.LOCATION = CV.LOCATION AND CD.DATE = CV.DATE
GROUP BY CD.LOCATION;

--Find the total number of vaccinations administered globally.

SELECT CONTINENT, SUM(NEW_VACCINATIONS) AS TOTAL_VACCINATIONS FROM COVIDVACCINATIONS
GROUP BY CONTINENT
ORDER BY TOTAL_VACCINATIONS DESC

--Identify the top 10 locations with the highest vaccination rates.

SELECT CD.LOCATION, SUM(CV.NEW_VACCINATIONS) AS TOTAL_VACCINATIONS,
       SUM(CD.NEW_CASES) AS TOTAL_CASES,
       SUM(CD.NEW_DEATHS) AS TOTAL_DEATHS, ROUND(SUM(CD.NEW_CASES)/NULLIF(SUM(CV.NEW_VACCINATIONS),0),2) AS VACCINATION_RATE FROM COVIDDEATHS CD
JOIN COVIDVACCINATIONS CV ON
CD.LOCATION = CV.LOCATION
AND CD.DATE = CV.DATE
GROUP BY CD.LOCATION
HAVING ROUND(SUM(CD.NEW_CASES)/NULLIF(SUM(CV.NEW_VACCINATIONS),0),2) IS NOT NULL
ORDER BY VACCINATION_RATE DESC
LIMIT 10

SELECT CD.CONTINENT, 
       SUM(CV.NEW_VACCINATIONS) AS TOTAL_VACCINATIONS,
       SUM(CD.NEW_CASES) AS TOTAL_CASES,
       SUM(CD.NEW_DEATHS) AS TOTAL_DEATHS,
       ROUND(SUM(CV.NEW_VACCINATIONS) / NULLIF(SUM(CD.NEW_CASES), 0) * 100, 2) AS VACCINATION_RATE
FROM COVIDDEATHS CD
JOIN COVIDVACCINATIONS CV 
ON CD.LOCATION = CV.LOCATION AND CD.DATE = CV.DATE
WHERE CD.CONTINENT IS NOT NULL  -- Excludes aggregated world data
GROUP BY CD.CONTINENT
ORDER BY TOTAL_VACCINATIONS DESC;

--Calculate the percentage of the population vaccinated per country.
SELECT CD.LOCATION, CD.POPULATION, SUM(CV.NEW_VACCINATIONS) AS TOTAL_VACCINATIONS, 
ROUND((SUM(CV.NEW_VACCINATIONS) /(CD.POPULATION) * 100), 2) AS PERCENT_POPULATION_VACCINATED
FROM COVIDDEATHS CD
JOIN COVIDVACCINATIONS CV 
ON CD.LOCATION = CV.LOCATION AND CD.DATE = CV.DATE
WHERE CD.POPULATION IS NOT NULL
GROUP BY CD.LOCATION, CD.POPULATION
ORDER BY PERCENT_POPULATION_VACCINATED DESC;

--Identify countries with the slowest vaccination rollout.
SELECT CD.LOCATION, CD.POPULATION, SUM(CV.NEW_VACCINATIONS) AS TOTAL_VACCINATIONS, 
ROUND((SUM(CV.NEW_VACCINATIONS) /(CD.POPULATION) * 100), 2) AS PERCENT_POPULATION_VACCINATED
FROM COVIDDEATHS CD
JOIN COVIDVACCINATIONS CV 
ON CD.LOCATION = CV.LOCATION AND CD.DATE = CV.DATE
WHERE CD.POPULATION IS NOT NULL
GROUP BY CD.LOCATION, CD.POPULATION
ORDER BY PERCENT_POPULATION_VACCINATED
LIMIT 10


--Find the effect of vaccination on COVID-19 death rates.
SELECT CD.LOCATION, 
       ROUND((SUM(CD.NEW_DEATHS) / NULLIF(SUM(CD.NEW_CASES), 0)) * 100, 2) AS OVERALL_DEATH_RATE,
       ROUND((SUM(CV.NEW_VACCINATIONS) / NULLIF(MAX(CD.POPULATION), 0)) * 100, 2) AS PERCENT_VACCINATED
FROM COVIDDEATHS CD
JOIN COVIDVACCINATIONS CV 
ON CD.LOCATION = CV.LOCATION AND CD.DATE = CV.DATE
WHERE CD.POPULATION IS NOT NULL
GROUP BY CD.LOCATION
ORDER BY PERCENT_VACCINATED DESC;

