SELECT COUNT(*) AS TOTAL_ROWS,
COUNT(*)- COUNT(POPULATION) AS POPULATED_POPULATION,
COUNT(*)- COUNT(ISO_CODE) AS ISO,
COUNT(*)- COUNT(LOCATION) AS LOCATION,
COUNT(*)- COUNT(CONTINENT) AS CONTINENT,
COUNT(*)- COUNT(DATE) AS DATE,
COUNT(*)- COUNT(TOTAL_CASES) AS TOTAL_CASE,
COUNT(*)- COUNT(NEW_CASES) AS NEW_CASES,
COUNT(*)- COUNT(TOTAL_DEATHS) AS TOTAL_DEATHS,
COUNT(*)- COUNT(NEW_DEATHS) AS NEW_DEATHS,
COUNT(*)- COUNT(REPRODUCTION_RATE) AS REPRODUCTION_RATE
FROM COVIDDEATHS

--SETTING CASES AND RECORDS TO 0 WHERE IT IS NULL--
UPDATE COVIDDEATHS
SET TOTAL_CASES=0
WHERE TOTAL_CASES IS NULL

UPDATE COVIDDEATHS
SET NEW_CASES=0
WHERE NEW_CASES IS NULL

UPDATE COVIDDEATHS
SET TOTAL_DEATHS=0
WHERE TOTAL_DEATHS IS NULL

UPDATE COVIDDEATHS
SET NEW_DEATHS=0
WHERE NEW_DEATHS IS NULL

UPDATE COVIDDEATHS
SET icu_patients = 0
WHERE ICU_PATIENTS IS NULL

UPDATE COVIDDEATHS
SET icu_patients_per_million = 0
WHERE icu_patients_per_million IS NULL	

UPDATE COVIDDEATHS
SET HOSP_PATIENTS = 0
WHERE HOSP_PATIENTS IS NULL

UPDATE COVIDDEATHS
SET hosp_patients_per_million = 0
WHERE hosp_patients_per_million IS NULL	

UPDATE COVIDDEATHS
SET weekly_icu_admissions= 0
WHERE weekly_icu_admissions	IS NULL

UPDATE COVIDDEATHS
SET weekly_hosp_admissions= 0
WHERE weekly_hosp_admissions IS NULL

UPDATE COVIDDEATHS
SET weekly_hosp_admissions_per_million= 0
WHERE weekly_hosp_admissions_per_million IS NULL


UPDATE CovidDeaths
SET continent = 
    CASE 
        WHEN location = 'World' THEN 'Global'
        WHEN location = 'Europe' THEN 'Europe'
        WHEN location = 'Asia' THEN 'Asia'
        WHEN location = 'Africa' THEN 'Africa'
        WHEN location = 'North America' THEN 'North America'
        WHEN location = 'South America' THEN 'South America'
        WHEN location = 'Oceania' THEN 'Oceania'
        ELSE 'Unknown' 
    END
WHERE continent IS NULL;

UPDATE COVIDDEATHS P1
SET POPULATION = (
SELECT P2.POPULATION FROM COVIDDEATHS P2
WHERE P2.LOCATION = P1.LOCATION
AND POPULATION IS NOT NULL
)
WHERE POPULATION IS NULL

UPDATE CovidDeaths
SET reproduction_rate = COALESCE(CovidDeaths.reproduction_rate, cte.prev_value)
FROM (
    SELECT location, date, reproduction_rate,
           LAG(reproduction_rate) OVER (PARTITION BY location ORDER BY date) AS prev_value
    FROM CovidDeaths
) AS cte
WHERE CovidDeaths.location = cte.location
AND CovidDeaths.date = cte.date
AND CovidDeaths.reproduction_rate IS NULL;



SELECT COUNT(*) AS TOTAL_ROWS,
COUNT(*)- COUNT(POPULATION) AS POPULATED_POPULATION,
COUNT(*)- COUNT(ISO_CODE) AS ISO,
COUNT(*)- COUNT(LOCATION) AS LOCATION,
COUNT(*)- COUNT(CONTINENT) AS CONTINENT,
COUNT(*)- COUNT(DATE) AS DATE,
COUNT(*)- COUNT(TOTAL_CASES) AS TOTAL_CASE,
COUNT(*)- COUNT(NEW_CASES) AS NEW_CASES,
COUNT(*)- COUNT(TOTAL_DEATHS) AS TOTAL_DEATHS,
COUNT(*)- COUNT(NEW_DEATHS) AS NEW_DEATHS,
COUNT(*)- COUNT(REPRODUCTION_RATE) AS REPRODUCTION_RATE
FROM COVIDDEATHS

